### ISSUE TITLE
Automatic refresh rate switching

### ISSUE THREAD

**Issue by xyzz** [mpv-android/mpv-android#12]

**Comment by xyzz** [comment]
To get current mode/list of modes:
https://developer.android.com/reference/android/view/Display.html#getSupportedModes()
https://developer.android.com/reference/android/view/Display.html#getMode()

To set a mode:
https://developer.android.com/reference/android/view/WindowManager.LayoutParams.html#preferredDisplayModeId

**Comment by dark-swordsman** [comment]
Is there any plan to implement this at all? It's been 7 years.

**Comment by jan-kleks** [comment]
This definitely would have been a nice feature to have. I just hope there would be a way for mpv-android to wait till a given display switches the refresh rate before beginning to play a movie...

Another video player I am using starts playing a movie before my projector changes the refresh rate and I am seeing just a black screen for quite a few seconds.

**Comment by moi15moi** [comment]
I believe we could call: https://developer.android.com/reference/android/view/Surface#setFrameRate(float,%20int)

The problem is what should we do with VFR video?

I'm wonder how the Adaptive refresh rate (https://source.android.com/docs/core/graphics/arr) perform.

**Comment by rohitghali** [comment]
Any update on if this will be implemented? It'll be a huge battery gain for mobile devices.

**Comment by jothi-prasath** [comment]
+1

**Comment by obscenelyvague** [comment]
When I think about it, dynamically setting refresh rate comes with a bunch of caveats. 

1. Container fps information is not always correct. We can use mpv estimated fps but that's a little slower and also not entirely accurate. 
2. You can't arbitrarily set refresh rate. Phones only support 2-5 refresh rate modes. 2 being the most common. This is because it's not only a matter of changing a number, each mode requires different calibration. Lower rates are often not tuned optimally for interactivity.
3. For 24 fps video do you prefer 60Hz or 120Hz? At 60Hz frame timing is worse. 
4. What do you do for VFR video, constantly poll?
5. At low refresh rate the UI is also obviously less smooth, sure you could have touch boost, but then that's a separate feature that has to be implemented and it's still probably a little jankier than running at max refresh rate at all times. 

On modern smartphones the difference between running at max or min refresh rate is negligible. I doubt it provides the infinite efficiency gains you may think it does. Most of the power use stems from elsewhere (decoding, rendering and screen brightness). 120Hz is a sane value that's more ideal than others for frame timing too.

Now, all that said, the implementation could be much more conservative in trying to use lower rates. I'll have to see how it works in practice.

**Comment by obscenelyvague** [comment]
Ok. I was intrigued too and decided to implement this feature to see how it works in practice. At first I implemented manual boosting. However, on Android 10+ there is a standard way it boosts on touch by default. The delays are controlled by `set_touch_timer_ms` and `set_idle_timer_ms` SurfaceFlinger system properties. Though what's nice about manual boosting is that if you hold the boost on for longer it can make the HRR switch gamma shift seem less distracting on some devices and also just keeps UI responsive for longer. The system delays are usually short. Whatever, not the app's concern so I ended up ditching the idea. As for the RR switching implementation itself it uses a scoring system to determine if it makes sense to ramp down. Initially also made an effort to handle VFR as well. This made things a fair bit complicated. Ditched that too. Now just relies on container fps. If you want to test this on your device the [link](https://segs.lol/XeBetl) downloads an APK. Installs separate from the official version as a standalone app.

**Comment by rohitghali** [comment]
> Ok. I was intrigued too and decided to implement this feature to see how it works in practice. At first I implemented manual boosting. However, on Android 10+ there is a standard way it boosts on touch by default. The delays are controlled by `set_touch_timer_ms` and `set_idle_timer_ms` SurfaceFlinger system properties. Though what's nice about manual boosting is that if you hold the boost on for longer it can make the HRR switch gamma shift seem less distracting on some devices and also just keeps UI responsive for longer. The system delays are usually short. Whatever, not the app's concern so I ended up ditching the idea. As for the RR switching implementation itself it uses a scoring system to determine if it makes sense to ramp down. Initially also made an effort to handle VFR as well. This made things a fair bit complicated. Ditched that too. Now just relies on container fps. If you want to test this on your device the [link](https://segs.lol/XeBetl) downloads an APK. Installs separate from the official version as a standalone app.

Tested this. Works flawlessly! Wonderful!

**Comment by WaruiDevil** [comment]
> When I think about it, dynamically setting refresh rate comes with a bunch of caveats.
> 
> 1. Container fps information is not always correct. We can use mpv estimated fps but that's a little slower and also not entirely accurate.
> 2. You can't arbitrarily set refresh rate. Phones only support 2-5 refresh rate modes. 2 being the most common. This is because it's not only a matter of changing a number, each mode requires different calibration. Lower rates are often not tuned optimally for interactivity.
> 3. For 24 fps video do you prefer 60Hz or 120Hz? At 60Hz frame timing is worse.
> 4. What do you do for VFR video, constantly poll?
> 5. At low refresh rate the UI is also obviously less smooth, sure you could have touch boost, but then that's a separate feature that has to be implemented and it's still probably a little jankier than running at max refresh rate at all times.
> 
> On modern smartphones the difference between running at max or min refresh rate is negligible. I doubt it provides the infinite efficiency gains you may think it does. Most of the power use stems from elsewhere (decoding, rendering and screen brightness). 120Hz is a sane value that's more ideal than others for frame timing too.
> 
> Now, all that said, the implementation could be much more conservative in trying to use lower rates. I'll have to see how it works in practice.

Thanks working perfectly

Here screenshot examples with 24fps vs 30fps vs 60fps videos

<img width="1938" height="1575" alt="Image" src="https://github.com/user-attachments/assets/db2e4308-27ed-48c4-94fc-61c2bc898674" />

**Comment by bozzis** [comment]
@obscenelyvague

thanks for that!
do you have a universal apk that can install on google tv?

**Comment by obscenelyvague** [comment]
V2 up with moar fixes.
[ARMv7/ARMv8 APK](https://segs.lol/prFCIF) or [Universal APK (including x86)](https://files.catbox.moe/8dbd1a.apk)

• Accounts for speed
• Fixed onResume being race-prone
• Bail early on single mode panels

**Comment by simongermani** [comment]
> V2 up with moar fixes. [ARMv7/ARMv8 APK](https://segs.lol/prFCIF) or [Universal APK (including x86)](https://files.catbox.moe/8dbd1a.apk)
> 
> • Accounts for speed • Fixed onResume being race-prone • Bail early on single mode panels

Tested on the original Fire TV 4K. Works well.
The only "bug" I noticed is that on 23.976 FPS content, the screen is set to 24Hz instead of 23.976Hz. My TV supports both, but I'm not sure if the native refresh rate switching apps like Amazon Prime do too.

Thank you so much for implementing this feature, it missing was the only reason I didn't use mpv on my Fire TV.

**Comment by Bilopo28** [comment]
> > V2 up with moar fixes. [ARMv7/ARMv8 APK](https://segs.lol/prFCIF) or [Universal APK (including x86)](https://files.catbox.moe/8dbd1a.apk)
> > • Accounts for speed • Fixed onResume being race-prone • Bail early on single mode panels
> 
> Tested on the original Fire TV 4K. Works well. The only "bug" I noticed is that on 23.976 FPS content, the screen is set to 24Hz instead of 23.976Hz. My TV supports both, but I'm not sure if the native refresh rate switching apps like Amazon Prime do too.
> 
> Thank you so much for implementing this feature, it missing was the only reason I didn't use mpv on my Fire TV.

Hello, does this change the actual refresh rate of your TV/ Firestick?
I tried it and only saw 24 Hz written in the MPV stats menu, but my TV is still set to 60 Hz. (I still experience some stuttering.)

**Comment by obscenelyvague** [comment]
V3, a.k.a. "This is it for a while unless someone finds something serious" edition.
[ARMv7/ARMv8 APK](https://segs.lol/H04RT0) or [Universal APK (including x86)](https://files.catbox.moe/c7xldc.apk)

• Dropped attempt to normalize NTSC rates

@simongermani Should work as expected now.

**Comment by moi15moi** [comment]
@obscenelyvague Have you tried to set `EGL_ANDROID_presentation_time` to see if it help when the screen doesn't support a refresh rate? See: https://developer.android.com/media/optimize/performance/frame-rate

**Comment by obscenelyvague** [comment]
@moi15moi I'm doing this all from the app side of things, in Kotlin. The frame presentation stuff, especially the 2 extensions for egl and vk should probably be implemented in libplacebo.

**Comment by simongermani** [comment]
> [@simongermani](https://github.com/simongermani) Should work as expected now.

Thank you very much! Tested and works perfectly now.

<br /><br />

> Hello, does this change the actual refresh rate of your TV/ Firestick? I tried it and only saw 24 Hz written in the MPV stats menu, but my TV is still set to 60 Hz. (I still experience some stuttering.)


<sup>Behaviour on current release version (display refresh rate stays at 59.94Hz)</sup>
<img width="202" height="156" alt="Image" src="https://github.com/user-attachments/assets/265ab4ed-d600-41c0-a8f7-39749e4d9e99" />

<sup>Behaviour on @obscenelyvague V2 (display refresh rate changes to 24Hz)</sup>
<img width="202" height="156" alt="Image" src="https://github.com/user-attachments/assets/c944694f-fd7a-47a2-9609-d69f608be528" />

<sup>Behaviour on @obscenelyvague V3 (display refresh rate changes to 23.976Hz)</sup>
<img width="202" height="156" alt="Image" src="https://github.com/user-attachments/assets/f63b86b1-aec9-4fc1-a003-19fcc4d8c667" />

These are set on the TV as well and there is no stuttering. Works perfectly even when I plug the Fire TV into my Denon AVR instead of directly into the TV.
This then (for me) fixes #1318 *


<sub>* at least the refresh rate matching part, although I wouldn't recommend matching resolution anyways, because TV's built-in scaling is usually much worse then mpv's</sub>

**Comment by Bilopo28** [comment]
> > [@simongermani](https://github.com/simongermani) Should work as expected now.
> 
> Thank you very much! Tested and works perfectly now.
> 
> > Hello, does this change the actual refresh rate of your TV/ Firestick? I tried it and only saw 24 Hz written in the MPV stats menu, but my TV is still set to 60 Hz. (I still experience some stuttering.)
> 
> Behaviour on current release version (display refresh rate stays at 59.94Hz) <img alt="Image" width="202" height="156" src="https://private-user-images.githubusercontent.com/51865047/643259202-265ab4ed-d600-41c0-a8f7-39749e4d9e99.jpg?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODgxMTU1ODAsIm5iZiI6MTc4ODExNTI4MCwicGF0aCI6Ii81MTg2NTA0Ny82NDMyNTkyMDItMjY1YWI0ZWQtZDYwMC00MWMwLWE4ZjctMzk3NDllNGQ5ZTk5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwODMwVDE4NDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4Y2JhN2VhY2Q0YTYxZGFhMThhMzkxNzU3ZmQ2ZDBmZDlhYTUwZWMwNzE0OWE5YjI4OTE2NTZkYjIzNzA1NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRmpwZWcifQ.xBar6EbdmHnH1HgHT8d1Ou2SngTV1Yr6JNst_eQeobc">
> 
> Behaviour on [@obscenelyvague](https://github.com/obscenelyvague) V2 (display refresh rate changes to 24Hz) <img alt="Image" width="202" height="156" src="https://private-user-images.githubusercontent.com/51865047/643259243-c944694f-fd7a-47a2-9609-d69f608be528.jpg?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODgxMTU1ODAsIm5iZiI6MTc4ODExNTI4MCwicGF0aCI6Ii81MTg2NTA0Ny82NDMyNTkyNDMtYzk0NDY5NGYtZmQ3YS00N2EyLTk2MDktZDY5ZjYwOGJlNTI4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwODMwVDE4NDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMGM5YWQwYjc4ZWQ3ZWE2MzEwYWU1YTA3OTI2ZjA4NjUyOGFkYzQ5YzI0Y2Y3MjNjNDM3OWQwYzY0ZTRhNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRmpwZWcifQ.DxUN8lOCHwUPw3HkJJHgpKCphpiMgaVx2H2sGR8AEZs">
> 
> Behaviour on [@obscenelyvague](https://github.com/obscenelyvague) V3 (display refresh rate changes to 23.976Hz) <img alt="Image" width="202" height="156" src="https://private-user-images.githubusercontent.com/51865047/643259263-f63b86b1-aec9-4fc1-a003-19fcc4d8c667.jpg?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODgxMTU1ODAsIm5iZiI6MTc4ODExNTI4MCwicGF0aCI6Ii81MTg2NTA0Ny82NDMyNTkyNjMtZjYzYjg2YjEtYWVjOS00ZmMxLWEwMDMtMTlmY2M0ZDhjNjY3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwODMwVDE4NDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxNDkyMmYyNDEwN2Q0MDdiOWM1ZGY0OWY3MzU1MGY4YTlhZTk2NzM2MjU4NjkxZGQzYTMzMDBiNGJmNTI2ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRmpwZWcifQ.U-UXdQk_QzCDcBgS15n6mKjXt_jBnSJpDafTgPvxqNw">
> 
> These are set on the TV as well and there is no stuttering. Works perfectly even when I plug the Fire TV into my Denon AVR instead of directly into the TV. This then (for me) fixes [#1318](https://github.com/mpv-android/mpv-android/issues/1318) *
> 
> * at least the refresh rate matching part, although I wouldn't recommend matching resolution anyways, because TV's built-in scaling is usually much worse then mpv's

With mpv V3

<img width="1536" height="855" alt="Image" src="https://github.com/user-attachments/assets/6734019a-879a-4054-bb54-9e13a8179bfe" />

As you can see, the tv stay at 60hz, do I have something to write inside mpv.conf ?
Sorry I'm kind of new to mpv and the way you configure it.

With jellyfin internal internal player and scaling set to tv

<img width="4000" height="2252" alt="Image" src="https://github.com/user-attachments/assets/c0937a6f-cfc3-4a60-9354-94b99e3d327c" />

With jellyfin internal internal player and scaling set to firestick (Or mpv ? I don't know what is doing the upscaling)

<img width="4000" height="2252" alt="Image" src="https://github.com/user-attachments/assets/46a13f2a-7fea-4688-aef1-a05bcc7bfb94" />

**Comment by rohitghali** [comment]
> > > [@simongermani](https://github.com/simongermani) Should work as expected now.
> > 
> > 
> > Thank you very much! Tested and works perfectly now.
> > > Hello, does this change the actual refresh rate of your TV/ Firestick? I tried it and only saw 24 Hz written in the MPV stats menu, but my TV is still set to 60 Hz. (I still experience some stuttering.)
> > 
> > 
> > Behaviour on current release version (display refresh rate stays at 59.94Hz) <img alt="Image" width="202" height="156" src="https://private-user-images.githubusercontent.com/51865047/643259202-265ab4ed-d600-41c0-a8f7-39749e4d9e99.jpg?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODgxMTU1ODAsIm5iZiI6MTc4ODExNTI4MCwicGF0aCI6Ii81MTg2NTA0Ny82NDMyNTkyMDItMjY1YWI0ZWQtZDYwMC00MWMwLWE4ZjctMzk3NDllNGQ5ZTk5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwODMwVDE4NDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4Y2JhN2VhY2Q0YTYxZGFhMThhMzkxNzU3ZmQ2ZDBmZDlhYTUwZWMwNzE0OWE5YjI4OTE2NTZkYjIzNzA1NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRmpwZWcifQ.xBar6EbdmHnH1HgHT8d1Ou2SngTV1Yr6JNst_eQeobc">
> > Behaviour on [@obscenelyvague](https://github.com/obscenelyvague) V2 (display refresh rate changes to 24Hz) <img alt="Image" width="202" height="156" src="https://private-user-images.githubusercontent.com/51865047/643259243-c944694f-fd7a-47a2-9609-d69f608be528.jpg?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODgxMTU1ODAsIm5iZiI6MTc4ODExNTI4MCwicGF0aCI6Ii81MTg2NTA0Ny82NDMyNTkyNDMtYzk0NDY5NGYtZmQ3YS00N2EyLTk2MDktZDY5ZjYwOGJlNTI4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwODMwVDE4NDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMGM5YWQwYjc4ZWQ3ZWE2MzEwYWU1YTA3OTI2ZjA4NjUyOGFkYzQ5YzI0Y2Y3MjNjNDM3OWQwYzY0ZTRhNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRmpwZWcifQ.DxUN8lOCHwUPw3HkJJHgpKCphpiMgaVx2H2sGR8AEZs">
> > Behaviour on [@obscenelyvague](https://github.com/obscenelyvague) V3 (display refresh rate changes to 23.976Hz) <img alt="Image" width="202" height="156" src="https://private-user-images.githubusercontent.com/51865047/643259263-f63b86b1-aec9-4fc1-a003-19fcc4d8c667.jpg?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODgxMTU1ODAsIm5iZiI6MTc4ODExNTI4MCwicGF0aCI6Ii81MTg2NTA0Ny82NDMyNTkyNjMtZjYzYjg2YjEtYWVjOS00ZmMxLWEwMDMtMTlmY2M0ZDhjNjY3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwODMwVDE4NDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxNDkyMmYyNDEwN2Q0MDdiOWM1ZGY0OWY3MzU1MGY4YTlhZTk2NzM2MjU4NjkxZGQzYTMzMDBiNGJmNTI2ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRmpwZWcifQ.U-UXdQk_QzCDcBgS15n6mKjXt_jBnSJpDafTgPvxqNw">
> > These are set on the TV as well and there is no stuttering. Works perfectly even when I plug the Fire TV into my Denon AVR instead of directly into the TV. This then (for me) fixes [#1318](https://github.com/mpv-android/mpv-android/issues/1318) *
> > 
> > * at least the refresh rate matching part, although I wouldn't recommend matching resolution anyways, because TV's built-in scaling is usually much worse then mpv's
> 
> With mpv V3
> 
> <img alt="Image" width="1536" height="855" src="https://private-user-images.githubusercontent.com/236476225/643262772-6734019a-879a-4054-bb54-9e13a8179bfe.webp?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODgxMTYzODYsIm5iZiI6MTc4ODExNjA4NiwicGF0aCI6Ii8yMzY0NzYyMjUvNjQzMjYyNzcyLTY3MzQwMTlhLTg3OWEtNDA1NC1iYjU0LTllMTNhODE3OWJmZS53ZWJwP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDgzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjA4MzBUMTg1NDQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmFhOWNiYmYyOThkMWZkZDg1OTdlZTc5ODNiYjNkOTNiZjI0MmJhMzJjZDNlM2E1ZGYwMTI1YTEyODFkOTNlYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmcmVzcG9uc2UtY29udGVudC10eXBlPWltYWdlJTJGd2VicCJ9.HBSjQCvm11kKGC83kP8FYwMWD2Ingv1YL79sUPVfFYY">
> As you can see, the tv stay at 60hz, do I have something to write inside mpv.conf ? Sorry I'm kind of new to mpv and the way you configure it.
> 
> With jellyfin internal internal player and scaling set to tv
> 
> <img alt="Image" width="2000" height="1126" src="https://private-user-images.githubusercontent.com/236476225/643262932-c0937a6f-cfc3-4a60-9354-94b99e3d327c.jpg?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODgxMTYzODYsIm5iZiI6MTc4ODExNjA4NiwicGF0aCI6Ii8yMzY0NzYyMjUvNjQzMjYyOTMyLWMwOTM3YTZmLWNmYzMtNGE2MC05MzU0LTk0Yjk5ZTNkMzI3Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDgzMFQxODU0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNWQ0YTZlODk4M2JlYzI2YTJkMzI1YTgxYTA0ZGIzODYxN2Y1ZTIyYzk0M2I1N2VlNDk5N2E0MzZmZDcwODMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZqcGVnIn0.y0f7cX46R277yHv2aGdiwcS5YgtEfKzX51Ltyqgl90E">
> With jellyfin internal internal player and scaling set to firestick (Or mpv ? I don't know what is doing the upscaling)
> 
> <img alt="Image" width="2000" height="1126" src="https://private-user-images.githubusercontent.com/236476225/643263041-46a13f2a-7fea-4688-aef1-a05bcc7bfb94.jpg?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODgxMTYzODYsIm5iZiI6MTc4ODExNjA4NiwicGF0aCI6Ii8yMzY0NzYyMjUvNjQzMjYzMDQxLTQ2YTEzZjJhLTdmZWEtNDY4OC1hZWYxLWEwNWJjYzdiZmI5NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDgzMFQxODU0NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDM1ZWY2ZjNkYzA3ZTE2MjYxOTAzNjFlMTA2ZTAwNWM0MGUwZWU0YzY5N2ZkMTkzNWIzY2U1MmU5NWM2YmYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZqcGVnIn0.OAlRhYXKKZGxWgGGyuUd3vZMt6otM2wnt_6FRErtIxI">

Just out of curiosity, what is the point of this in a fire stick? For mobile devices this preserves valuable battery life. What's the purpose on a fire stick and a tv? It is already plugged in to the wall socket right?

**Comment by simongermani** [comment]
> As you can see, the tv stay at 60hz, do I have something to write inside mpv.conf ? Sorry I'm kind of new to mpv and the way you configure it.

Interesting, it seems your TV reports 23.976Hz but actually runs at 60Hz.
The only thing difference I could spot is that my Fire TV defaults to copy on hardware decoding. You can try to enable that manually by setting
`hwdec=mediacodec-copy`
in mpv.conf
But I don't know if that would change anything, since I can't replicate this bug

> Just out of curiosity, what is the point of this in a fire stick? For mobile devices this preserves valuable battery life. What's the purpose on a fire stick and a tv? It is already plugged in to the wall socket right?

Matching refresh rates enables stutter-free playback. Because 24 doesn't fit in 60 cleanly, usually a frame has to be repeated sometimes. Some people are very sensitive to this. You can read more in the [mpv wiki](https://github.com/mpv-player/mpv/wiki/Display-synchronization)

**Comment by Bilopo28** [comment]
> > As you can see, the tv stay at 60hz, do I have something to write inside mpv.conf ? Sorry I'm kind of new to mpv and the way you configure it.
> 
> Interesting, it seems your TV reports 23.976Hz but actually runs at 60Hz. The only thing difference I could spot is that my Fire TV defaults to copy on hardware decoding. You can try to enable that manually by setting `hwdec=mediacodec-copy` in mpv.conf But I don't know if that would change anything, since I can't replicate this bug
> 
> > Just out of curiosity, what is the point of this in a fire stick? For mobile devices this preserves valuable battery life. What's the purpose on a fire stick and a tv? It is already plugged in to the wall socket right?
> 
> Matching refresh rates enables stutter-free playback. Because 24 doesn't fit in 60 cleanly, usually a frame has to be repeated sometimes. Some people are very sensitive to this. You can read more in the [mpv wiki](https://github.com/mpv-player/mpv/wiki/Display-synchronization)

I gave a try to hwdec=mediacodec-copy, to no avail. Still 60HZ. What's your tv btw ?

> V3, a.k.a. "This is it for a while unless someone finds something serious" edition. [ARMv7/ARMv8 APK](https://segs.lol/H04RT0) or [Universal APK (including x86)](https://files.catbox.moe/c7xldc.apk)
> 
> • Dropped attempt to normalize NTSC rates
> 
> [@simongermani](https://github.com/simongermani) Should work as expected now.

Maybe Obscenelyvague has an idea

**Comment by rohitghali** [comment]
Where is the code for this? I mean, which branch are you using to make the changes?

**Comment by WaruiDevil** [comment]
@obscenelyvague is this still not complete? If did then please PR it.
