### ISSUE TITLE
Navigation bar offset incorrectly applied to player UI

### ISSUE THREAD

**Issue by da3dsoul1** [mpv-android/mpv-android#744]
In version 2023-06-04 a potential fix for navigation bar was introduced, but it also broke the interface for people who were having the pill disabled since the begining, now the osc is a bit lifted up, is there a possibility to add a toggle option to make it stick back to the bottom like it was in previous versions?
Latest update with a problem:
![photo_2023-07-07_20-22-18](https://github.com/mpv-android/mpv-android/assets/111184581/492afe5b-ed60-4e7c-8400-a83cbc81075f)
How it should be from previous versions:
![image](https://github.com/mpv-android/mpv-android/assets/111184581/217c39fe-ebea-42ca-9688-522a2567099e)

**Comment by sfan5** [comment]
Where is the display cutout located in your screenshots? Which orientation is your device in?
Please also try the APK [from here](https://github.com/mpv-android/mpv-android/actions/runs/5270523293) and check if it's already fixed by now.

**Comment by da3dsoul1** [comment]
I don't have any display cutouts, my device is 9T Pro, orientation is default landscape. The issue still persists in the apk you just provided. Perhaps I didn't explain it clear enough, I have a setting in my rom that allows me to hide the gesture pill and navigation bar padding, but the issue is still there kinda with them enabled(default settings), the small space in-between is still there.

Your apk with navigation bar enabled(default settings):
![image](https://github.com/mpv-android/mpv-android/assets/111184581/00187f72-d26a-4229-a507-39122e4d87c7)
Navigation bar disabled(I want it to stick to the bottom completely like it did in previous versions):
![image](https://github.com/mpv-android/mpv-android/assets/111184581/fe04e647-12a8-46ae-8719-0075d1b563d8)

**Comment by sfan5** [comment]
Ah, you're describing a different bug than what I thought.
I have seen the weird offset for android versions with navigation bar in my testing too but so far I assumed that this didn't work before either.

**Comment by da3dsoul1** [comment]
Yup. sorry about describing it wrong, is it possible to revert the offset back to how it was in 2023-02-27-release and older? Or perhaps a toggle in the settings for manually setting the desired value.

**Comment by biopsin** [comment]
confirmed on xperia 1ii (no cutout) mpv-android  v.2023.06.14, theres a gap now in both portrait and landscape when enable controls on bottom.

**Comment by aicynide** [comment]
> I don't have any display cutouts, my device is 9T Pro, orientation is default landscape. The issue still persists in the apk you just provided. Perhaps I didn't explain it clear enough, I have a setting in my rom that allows me to hide the gesture pill and navigation bar padding, but the issue is still there kinda with them enabled(default settings), the small space in-between is still there.
> 
> Your apk with navigation bar enabled(default settings): ![image](https://user-images.githubusercontent.com/111184581/251970857-00187f72-d26a-4229-a507-39122e4d87c7.png) Navigation bar disabled(I want it to stick to the bottom completely like it did in previous versions): ![image](https://user-images.githubusercontent.com/111184581/251970879-fe04e647-12a8-46ae-8719-0075d1b563d8.png)

How is your progress bar thick? Post apk

**Comment by da3dsoul1** [comment]
@aicynide it's fixed and working as it should with the latest update.

**Comment by aicynide** [comment]
@da3dsoul1 that's not what I asked how to get seekbar like you?

**Comment by aicynide** [comment]
@da3dsoul1 waiting for the apk
