### ISSUE TITLE
Pressing back button in any directory changes it to the one selected using "OPEN DOCUMENT TREE"

### ISSUE THREAD

**Issue by madscientist16** [mpv-android/mpv-android#898]
### Important information
Android version: 14
mpv-android version: 2024-04-09

### Description
Steps to reproduce:
1. Open a folder using OPEN DOCUMENT TREE
2. Go to any directory
3. Press back button or use gesture to go back

### Additional information
In the 2023-11-30 version this happens when backing out of a video. It got fixed in version 2024-04-09.

**Comment by sfan5** [comment]
This never worked correctly, not sure how that slipped past. Fixed now.

**Comment by madscientist16** [comment]
For whatever reason the latest release available on play store for me is 2024-04-09 so I decided to get the latest release from github. This issue is still present if I open a video and then back out.

mpv android version: 2024-05-24

**Comment by madscientist16** [comment]
I do have it installed. I uninstalled the play store version before installing it. First backing out of the video takes me to the video directory. If I back out again it takes me back to the directory selected with OPEN DOCUMENT TREE.

**Comment by sfan5** [comment]
That's a different and very specific case.
Navigating document trees backwards requires remembering "where you went". This information is lost when the file picker closes.

Not impossible to fix but somewhat annoying.
